### ISSUE TITLE
Perhaps, some improvements to wording

### ISSUE THREAD

**Issue by rodiongork-atwork** [medikoo/es5-ext#140]
Mariusz, Hi again! This time I have some thoughts on my own accord (rather than having to resolve difficulties for my company).

I reviewed "the manifest" carefully. I feel that it intends to do good, to provide help (at least in being informative) - but due to its style feels rather offensive and spam-like, which probably is increasing user's outcry and undermines your goal :) If you are open to suggestions, just tell. Otherwise feel free to close the ticket (or better remove) to prevent more flame.

E.g. one of the first I'd suppose drop the explanation about Tor, **replacing it with some links to some news sites you regard as trustworthy and least biased**. Motivation is simple - everyone (of those whom you address - IT-fellows) knows what is Tor, how to use VPN or Proxy. Programmers don't watch a lot of TV nowadays, rather getting news from Telegram channels :)

(to clarify - onion link you included doesn't work well with VPN or Proxy, of course, so you may rather to include direct links to whatever you prefer - people who are curious shall have no troubles visiting them, be sure)

**Comment by medikoo** [comment]
@rodiongork-genestack thanks for this comment.

Yes, at this point I'm not sure if its wording is best. Initially, I've (naively) assumed that majority of respondents will be the ones reluctant to war and will take this as a friendly reach out, and something that will help them clear the doubts, but it appears that for the majority it appears as something aggressive, a form of attack on them.

I've got one comment from a developer (who supports the manifest,) working in one of the sanctioned Russian banks and he inclined that for most, the impression is, is like we would see the message sent b they ISIS (the level of brainwashing is tremendous)

> E.g. one of the first I'd suppose drop the explanation about Tor, replacing it with some links to some news sites you regard as trustworthy and least biased. 

Are there any, to which they have free access? Or should we just add the note, that they should use VPN or TOR to access it (without adding links to the TOR browser)? What sites would you suggest? (I believe it's best if they're in Russian, and my knowledge of that is limited)

Maybe there's some good Telegram channel which works?

> to clarify - onion link you included doesn't work well with VPN or Proxy,

It's dedicated for TOR browser (won't work in regular one), and it's what I see when I open it through TOR:

<img width="1266" alt="Screenshot 2022-04-02 at 11 19 14" src="https://user-images.githubusercontent.com/122434/161376623-0b835498-88cb-42c5-9510-d08b70dfd2c7.png">

It works quite well, but in Russia users need to not only download TOR browser but also setup it with custom relays (and other links which AFAIK works in Russia provides solid info on that)

--- 

Anyway, how would you improve the wording?  If we can make it, so it breaks the right message through and at the same time doesn't feel hostile, I'm all for it.

**Comment by nomanner1988** [comment]
Black lives no longer matter?

**Comment by rodiongork-genestack** [comment]
Mariusz, Dzien Dobry - and sorry for delay with the response!

> I've (naively) assumed that majority of respondents will be the ones reluctant to war and will take this as a friendly reach out

I dare say you guessed 90% correct, ha-ha-ha :) If you want this to be clarified - "inteligencja" class is generally much against the current situation (and many of them are generally "opposition"-minded). More support of government and this sad war is among common people, naturally. And normally there are more common people than IT-workers, of course :)

Thus you really mainly address people who are on your side. You most probably got a heap of unpleasant comments from those who are not (or simply dislike bringing politics to opensource), but you understand that those who agree generally have nothing special to comment.

> the impression is, is like we would see the message sent b they ISIS

I dare say, from "aside perspective" it much looks like "someone was hacked", especially due to Cyrillic letters :) Generally expect IT-specialists working with github / npm having proficiency in English so it should be all right either to switch to English completely, or add brief "foreword" in English. E.g.

_Author of such and such repository / library feels much concern in the current situation in Europe and left this manifest / appeal here to be read to IT-colleagues in Russia. Sorry for possible inconvenience and don't think anything is hacked._

(this makes additional sense as not everyone of your targeted audience reads / speaks Russian fluently)

> Are there any, to which they have free access? Or should we just add the note, that they should use VPN or TOR to access it

Hm-m-m :) Don't be surprised (you can easily check this anyway by using russian vpn or proxy), but there are no significant restrictions (currently) over internet usage. Some parts of BBC are blocked, Twitter, FB and Instagram (these two simply for their queer policy changes). Few Ukrainian media. But most restrictions are imposed on local media, which is natural - not foreign.

CNN, Washington Post, Independent, even Polskie Radio - all this is freely accessible for whoever cares. Also as I probably mentioned people rely heavily on certain Telegram channels, which couldn't be blocked (though for me it seems they often provide biased information). Blocked local media also operate in Telegram sometimes.

> What sites would you suggest? 

Honestly, I'd personally stay away from UK news media. Not sure what is happening, it seems somehow related to their internal political struggles, but they feel as much "propagandish" as russian. And Russian IT-folks are quite suspicious to something which looks like propaganda - either their own, or foreign :) Thus anything in English from French / German etc media may look more credible for them. Helsinki Times in my personal opinion is the best - but it is much calmer compared to others. Since manifest mentions effect on Poland, I suppose English pages of Polskie Radio website (or other Polish news?) shall look "proper" here too.

> Anyway, how would you improve the wording?

Ahm. Almost forgot where we started, sorry :) Let's see

1. The last phrase "stop the war / putin" sounds as if the people who read this are allegedly dealing in war. As mentioned above, they are most probably of anti-war mood, so better would be "please **help** stop the war / spread the information"
2. I'd drop mentioning of Zelenski and Putin :) The goal for manifest is to stop the war, not to make politics - so let it look less political. And more "hidden motive" - I suspect while Russian people are ready to blame their govt themselves, they don't like when others blame their govt. It's true about any nation to some degree, though it's quite ridiculous fact, of course :)
3. Perhaps exact numbers of victims also better be dropped. Feel free to outline them as thousands or like this: "It's hard to tell exactly, but number of victims on both sides reaches thousands! Millions are fleeing their city or their country with no other belonging than their children." Also this shall spare you from updating statistics.
4. "All the world condemns" and "unheard-of sanctions" are extremely "propagandish" even to my taste, sorry. It sounds much like TV, especially since it is clear that not world is to certain extent split or indifferent on the topic. And about the sanctions you need not write, your addressees know better of them, right? :) This passage I'd recommend to drop completely.
5. On the other hand it may be good to emphasize humanitarian impact: "Prices grew every day, traffic of life-important goods is disrupted, this much affects poor people and those requiring medical care".

In other words it would be great to stress that you are calling for peace and would like people to join your call and spreading info (e.g. rather fighting not "restrictions" but people's "carelessness" of the events).

Too much thoughts, sorry. Feel free to dispose this as gibberish if you don't like it - and sorry for taking your time :)

P.S. Perhaps, consider removing geo-location condition. I think if you add English preface to manifest, it is worth of being shown to anyone. This will serve two goals, even three - first it looks less "hacky"; second - thousands of Russians you are targeting left the country temporarily (or for open term) by now; third - I honestly believe stopping the war requires international efforts (and by now I regretfully don't see much willing to it on either side, among politicians I mean).

**Comment by medikoo** [comment]
@rodiongork-genestack that's very very valuable input, great thanks for all these input.

I'd like to update the manifest wording, as your suggestions feel mostly right to me. Do you know Russian well? Or maybe you know a native Russian who would be keen to help on that? (we can do it privately via email if preferred)

> P.S. Perhaps, consider removing geo-location condition.

This one I'd prefer to keep on, as for those not involved it's unwanted spam-like noise, and this message is specifically directed to Russians in Russia, I don't want to change that.
